// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace QRCodeGeneraterForDotNet
{
	public class QRCodeGeneraterForDotNet
	{
		
		public int Width { get; set; }
		public int Height { get; set; }
		
		public writeableBitmap GenerateQRCode (string source,short width,short height)
		{
			Width  = width;
			Height = height;
			string URL = makeURL(Width,Height);
			
		}
		
		proted writeableBitmap getImageFromURL(string url)
		{
			HttpClient client = new HttpClient();
			var result = client.getAsync(url);
			if (!result.IsSuccesCode)
			{
				throw new Exception("画像の取得に失敗しました");
			}
			
			
		}
		
		protected string makeURL(string source ,short width,short height)
		{
			string base = "http://chart.googleapis.com/chart?cht=qr&";
			
			base + "chl=" + source + "&";
			base + "chs=" + width + "x" + height;
			return base;
			
		}
	}
}

