using System;
using Windows.UI.Xaml.Media.Imaging;
using System.IO;
using System.Runtime.InteropServices.WindowsRuntime;

namespace QRCodeGenerater
{
    // ------------------------------------------------------------------------------
    //  <autogenerated>
    //      This code was generated by a tool.
    //      Mono Runtime Version: 4.0.30319.17020
    // 
    //      Changes to this file may cause incorrect behavior and will be lost if 
    //      the code is regenerated.
    //  </autogenerated>
    // ------------------------------------------------------------------------------
    using System;
    using System.IO;
    using System.Net.Http;
    using System.Threading.Tasks;

    namespace QRCodeGeneraterForDotNet
    {
        public class QRCodeGenerater
        {
            public int Width { get; set; } = 256;
            public int Height { get; set; } = 256;

            public async Task<WriteableBitmap> GenerateQRCode(string source)
            {
                string URL = makeURL(source);

                var bitmap = await getImageFromURL(URL);
                return bitmap ?? new WriteableBitmap(Width, Height);
            }

            protected async Task<WriteableBitmap> getImageFromURL(string url)
            {
                HttpClient client = new HttpClient();
                var response = await client.GetAsync(url);

                if (!response.IsSuccessStatusCode)
                {
                    throw new Exception("画像の取得に失敗しました");
                }

                byte[] resultByte = await response.Content.ReadAsByteArrayAsync();


                var bitmap = new WriteableBitmap(Width, Height);

                using (var pixelStream = bitmap.PixelBuffer.AsStream())
                {
                    pixelStream.Seek(0, SeekOrigin.Begin);
                    pixelStream.Write(resultByte, 0, resultByte.Length);
                }

                return bitmap;

            }

            protected string makeURL(string source)
            {
                string result = "http://chart.googleapis.com/chart?cht=qr";

                result += "&" + "chl=" + source;
                result += "&" + "chs=" + Width + "x" + Height;
                return result;

            }
        }
    }


}
